// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: search.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace DataBridge.Search {
  public static partial class SearchService
  {
    static readonly string __ServiceName = "Search.SearchService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DataBridge.Search.SearchQueryRequest> __Marshaller_Search_SearchQueryRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DataBridge.Search.SearchQueryRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DataBridge.Search.GameListResponse> __Marshaller_Search_GameListResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DataBridge.Search.GameListResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DataBridge.Search.GameIndexRequest> __Marshaller_Search_GameIndexRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DataBridge.Search.GameIndexRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DataBridge.Search.GameInfoResponse> __Marshaller_Search_GameInfoResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DataBridge.Search.GameInfoResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DataBridge.Search.SearchQueryRequest, global::DataBridge.Search.GameListResponse> __Method_GetAutocomplete = new grpc::Method<global::DataBridge.Search.SearchQueryRequest, global::DataBridge.Search.GameListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAutocomplete",
        __Marshaller_Search_SearchQueryRequest,
        __Marshaller_Search_GameListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DataBridge.Search.SearchQueryRequest, global::DataBridge.Search.GameListResponse> __Method_GetFullSearch = new grpc::Method<global::DataBridge.Search.SearchQueryRequest, global::DataBridge.Search.GameListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetFullSearch",
        __Marshaller_Search_SearchQueryRequest,
        __Marshaller_Search_GameListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DataBridge.Search.GameIndexRequest, global::DataBridge.Search.GameInfoResponse> __Method_GetGameDetail = new grpc::Method<global::DataBridge.Search.GameIndexRequest, global::DataBridge.Search.GameInfoResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetGameDetail",
        __Marshaller_Search_GameIndexRequest,
        __Marshaller_Search_GameInfoResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DataBridge.Search.SearchReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SearchService</summary>
    [grpc::BindServiceMethod(typeof(SearchService), "BindService")]
    public abstract partial class SearchServiceBase
    {
      /// <summary>
      /// 1. 얕은 탐색 (Autocomplete)
      /// Pruning Trie를 사용해 인기순 상위 5개 즉시 반환
      /// URL 예시: GET /search/autocomplete/batt
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DataBridge.Search.GameListResponse> GetAutocomplete(global::DataBridge.Search.SearchQueryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 2. 깊은 탐색 (Full Search)
      /// 전체 리스트를 뒤져서(AND/OR) 조건에 맞는 결과 반환
      /// URL 예시: GET /search/full/battle ground
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DataBridge.Search.GameListResponse> GetFullSearch(global::DataBridge.Search.SearchQueryRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 3. 상세 정보 조회 (Detail)
      /// 사용자가 리스트를 클릭했을 때 호출 (캐시 -> DB -> 스팀)
      /// URL 예시: GET /search/game/105
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DataBridge.Search.GameInfoResponse> GetGameDetail(global::DataBridge.Search.GameIndexRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(SearchServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetAutocomplete, serviceImpl.GetAutocomplete)
          .AddMethod(__Method_GetFullSearch, serviceImpl.GetFullSearch)
          .AddMethod(__Method_GetGameDetail, serviceImpl.GetGameDetail).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SearchServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetAutocomplete, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DataBridge.Search.SearchQueryRequest, global::DataBridge.Search.GameListResponse>(serviceImpl.GetAutocomplete));
      serviceBinder.AddMethod(__Method_GetFullSearch, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DataBridge.Search.SearchQueryRequest, global::DataBridge.Search.GameListResponse>(serviceImpl.GetFullSearch));
      serviceBinder.AddMethod(__Method_GetGameDetail, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DataBridge.Search.GameIndexRequest, global::DataBridge.Search.GameInfoResponse>(serviceImpl.GetGameDetail));
    }

  }
}
#endregion
