// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: search.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace DataBridge.Search {
  public static partial class SearchService
  {
    static readonly string __ServiceName = "Search.SearchService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DataBridge.Search.SearchNameRequest> __Marshaller_Search_SearchNameRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DataBridge.Search.SearchNameRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DataBridge.Search.GameLabelResponse> __Marshaller_Search_GameLabelResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DataBridge.Search.GameLabelResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::DataBridge.Search.GameIndexRequest> __Marshaller_Search_GameIndexRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::DataBridge.Search.GameIndexRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DataBridge.Search.SearchNameRequest, global::DataBridge.Search.GameLabelResponse> __Method_GetGameBySearchName = new grpc::Method<global::DataBridge.Search.SearchNameRequest, global::DataBridge.Search.GameLabelResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetGameBySearchName",
        __Marshaller_Search_SearchNameRequest,
        __Marshaller_Search_GameLabelResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::DataBridge.Search.GameIndexRequest, global::DataBridge.Search.GameLabelResponse> __Method_GetGameByIndex = new grpc::Method<global::DataBridge.Search.GameIndexRequest, global::DataBridge.Search.GameLabelResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetGameByIndex",
        __Marshaller_Search_GameIndexRequest,
        __Marshaller_Search_GameLabelResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::DataBridge.Search.SearchReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SearchService</summary>
    [grpc::BindServiceMethod(typeof(SearchService), "BindService")]
    public abstract partial class SearchServiceBase
    {
      /// <summary>
      /// 1. 얕은 탐색 (주소: /search/name/검색어)
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DataBridge.Search.GameLabelResponse> GetGameBySearchName(global::DataBridge.Search.SearchNameRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// 2. 깊은 탐색 (주소: /search/index/번호)
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::DataBridge.Search.GameLabelResponse> GetGameByIndex(global::DataBridge.Search.GameIndexRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(SearchServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetGameBySearchName, serviceImpl.GetGameBySearchName)
          .AddMethod(__Method_GetGameByIndex, serviceImpl.GetGameByIndex).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SearchServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetGameBySearchName, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DataBridge.Search.SearchNameRequest, global::DataBridge.Search.GameLabelResponse>(serviceImpl.GetGameBySearchName));
      serviceBinder.AddMethod(__Method_GetGameByIndex, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::DataBridge.Search.GameIndexRequest, global::DataBridge.Search.GameLabelResponse>(serviceImpl.GetGameByIndex));
    }

  }
}
#endregion
